[project]
name = "torquefield"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nvidia-cuda-runtime-cu11>=11.8.89",
    "nvidia-cudnn-cu11>=9.10.2.21",
    "onnx>=1.23.0",
    "onnxscript>=0.7.2",
    "pillow>=12.3.0",
    "requests>=2.34.2",
    "tensorflow>=2.21.0",
    "tensorrt>=11.3.0.99",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]
